bmap-tools: update SCR_URI to use main branch
The upstream repository has renamed from master branch to main. This
causes fetch errors like:

ERROR: bmap-tools-native-3.6+gitAUTOINC+c0673962a8-r0 do_fetch: Fetcher failure: Unable to find revision c0673962a8ec1624b5189dc1d24f33fe4f06785a in branch master even from upstream
ERROR: bmap-tools-native-3.6+gitAUTOINC+c0673962a8-r0 do_fetch: Fetcher failure for URL: 'git://github.com/intel/bmap-tools;branch=master;protocol=https'. Unable to fetch URL from any source.

Fix it by adding a bbappend replacing 'master' with 'main' in SRC_URI.

Signed-off-by: Alexander Herfurtner <alexander.h@variscite.com>